# Generated by Django 4.1 on 2022-08-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('Address', models.TextField(max_length=240)),
                ('student', models.IntegerField()),
            ],
        ),
    ]
