# Generated by Django 4.1 on 2022-08-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Address',
            field=models.CharField(max_length=240),
        ),
    ]
